In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. 
They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without 
reinventing the wheel.

With libraries, pre-written code can be reused instead of creating a new one for every project. 
Python libraries offer numerous functionalities such as deep learning and 
natural language processing that can optimize development processes while also making it easier for teams to collaborate on projects.

In [ ]:
# 2. What is the ^ifference between Numpy array and List

The biggest difference is NumPy arrays use fewer resources than Python lists, 
which becomes important when storing a large amount of data. 
If you're working with thousands of elements, Python lists will be fine for most purposes.

In summary, Python lists are more suitable for general-purpose tasks requiring flexibility, 
while NumPy arrays excel in numerical computation and tasks involving large datasets due to their efficiency and optimized operation


In [8]:
# 3. Find the shape, size and ^imension of the following array?
import numpy as np
x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(x.shape)
print(x.size)
print(x.ndim)


(3, 4)
12
2


In [10]:
# 4. Write python code to access the first row of the following array?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(x[0])


[1 2 3 4]


In [13]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(x[2][3])

12


In [15]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

x[0::2]



array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [19]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1

np.random.random((3,3))

array([[0.06559918, 0.56781559, 0.75785612],
       [0.48577908, 0.75403674, 0.27330122],
       [0.41608387, 0.63963239, 0.24644427]])

In [ ]:
# 8. Describe the ^ifference between np.random.rand and np.random.randn

In summary, randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, 
while `rand` generates numbers from a uniform distribution between 0 and 1
np.random.rand(2,4)
np.random.randn(2,4)

In [22]:
# 9. Write code to increase the dimension of the following array?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
x.resize(2,3,2)

In [25]:
# 10. How to transpose the following array in NumPy?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [47]:
# 11. Consider the following matrix:

A2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
B2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])


In [48]:
A2+B2
A2*B2
A2/B2
A2-B2


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
# 12.  Which function in Numpy can be use^ to swap the byte order of an array?

x=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
x.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

In [ ]:
# 13.  What is the significance of the np.linalg.inv function?

We use numpy. linalg. inv() function to calculate the inverse of a matrix.
The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [ ]:
# 14. What does the np.reshape function do, and how is it used


Change an Array's Shape Using NumPy reshape() NumPy's reshape() enables you to change the shape of an array into another compatible shape.

arr.reshape(4,5)

In [ ]:
# 15. What is broa^casting in Numpy?

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.

Arithmetic operations on arrays are usually done on corresponding elements.
If two arrays are of exactly the same shape, then these operations are smoothly performed.